//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfModelMigrations.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EfModelMigrations.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly &apos;{0}&apos;. .
        /// </summary>
        internal static string BaseRunner_AssemblyNotFound {
            get {
                return ResourceManager.GetString("BaseRunner_AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project failed to build..
        /// </summary>
        internal static string CannotBuildProject {
            get {
                return ResourceManager.GetString("CannotBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create instance of type {0}..
        /// </summary>
        internal static string CannotCreateInstance {
            get {
                return ResourceManager.GetString("CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find configuration class in project..
        /// </summary>
        internal static string CannotFindConfiguration {
            get {
                return ResourceManager.GetString("CannotFindConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name not specified..
        /// </summary>
        internal static string CommandNameNotSpecified {
            get {
                return ResourceManager.GetString("CommandNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model migrations was successfully enabled in current project..
        /// </summary>
        internal static string ModelEnableSuccessfull {
            get {
                return ResourceManager.GetString("ModelEnableSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model migrations was already enabled..
        /// </summary>
        internal static string ModelMigrationsAlreadyEnabled {
            get {
                return ResourceManager.GetString("ModelMigrationsAlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find any migration to apply or revert..
        /// </summary>
        internal static string NoMigrationsToMigrate {
            get {
                return ResourceManager.GetString("NoMigrationsToMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path must be relative to project directory..
        /// </summary>
        internal static string ProjectExtensions_PathMustBeRelative {
            get {
                return ResourceManager.GetString("ProjectExtensions_PathMustBeRelative", resourceCulture);
            }
        }
    }
}
