// <auto-generated />

namespace EfModelMigrations.Resources
{
    using System;
    using System.CodeDom.Compiler;
    using System.Globalization;
    using System.Resources;
    using System.Reflection;
    using System.Threading;

    // <summary>
    // Strongly-typed and parameterized string resources.
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal static class Strings
    {
        // <summary>
        // A string like "Cannot apply model migration. See inner exception for details."
        // </summary>
        internal static string ApplyMigrationError
        {
            get { return EntityRes.GetString(EntityRes.ApplyMigrationError); }
        }

        // <summary>
        // A string like "Could not load assembly '{0}'."
        // </summary>
        internal static string BaseRunner_AssemblyNotFound(object p0)
        {
            return EntityRes.GetString(EntityRes.BaseRunner_AssemblyNotFound, p0);
        }

        // <summary>
        // A string like "Project failed to build."
        // </summary>
        internal static string CannotBuildProject
        {
            get { return EntityRes.GetString(EntityRes.CannotBuildProject); }
        }

        // <summary>
        // A string like "Cannot create command instance. Command {0} not found."
        // </summary>
        internal static string CannotCreateCommandInstance(object p0)
        {
            return EntityRes.GetString(EntityRes.CannotCreateCommandInstance, p0);
        }

        // <summary>
        // A string like "Cannot create instance of type {0}."
        // </summary>
        internal static string CannotCreateInstance(object p0)
        {
            return EntityRes.GetString(EntityRes.CannotCreateInstance, p0);
        }

        // <summary>
        // A string like "Cannot find class with name {0} in model project."
        // </summary>
        internal static string CannotFindClassInModelProject(object p0)
        {
            return EntityRes.GetString(EntityRes.CannotFindClassInModelProject, p0);
        }

        // <summary>
        // A string like "Cannot find configuration class in project."
        // </summary>
        internal static string CannotFindConfiguration
        {
            get { return EntityRes.GetString(EntityRes.CannotFindConfiguration); }
        }

        // <summary>
        // A string like "Cannot find enum with name {0} in model project."
        // </summary>
        internal static string CannotFindEnumInModelProject(object p0)
        {
            return EntityRes.GetString(EntityRes.CannotFindEnumInModelProject, p0);
        }

        // <summary>
        // A string like "Cannot find migration {0}."
        // </summary>
        internal static string CannotFindMigration(object p0)
        {
            return EntityRes.GetString(EntityRes.CannotFindMigration, p0);
        }

        // <summary>
        // A string like "Cannot find migration Id."
        // </summary>
        internal static string CannotFindMigrationId
        {
            get { return EntityRes.GetString(EntityRes.CannotFindMigrationId); }
        }

        // <summary>
        // A string like "Command name not specified."
        // </summary>
        internal static string CommandNameNotSpecified
        {
            get { return EntityRes.GetString(EntityRes.CommandNameNotSpecified); }
        }

        // <summary>
        // A string like "Name of class for new properties is missing."
        // </summary>
        internal static string Commands_AddProperties_ClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_AddProperties_ClassNameMissing); }
        }

        // <summary>
        // A string like "No properties was specified to add to class {0}."
        // </summary>
        internal static string Commands_AddProperties_NoProperties(object p0)
        {
            return EntityRes.GetString(EntityRes.Commands_AddProperties_NoProperties, p0);
        }

        // <summary>
        // A string like "Name od the new class is missing."
        // </summary>
        internal static string Commands_CreateClass_ClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_CreateClass_ClassNameMissing); }
        }

        // <summary>
        // A string like "Properties for the new class {0} is missing."
        // </summary>
        internal static string Commands_CreateClass_PropertiesMissing(object p0)
        {
            return EntityRes.GetString(EntityRes.Commands_CreateClass_PropertiesMissing, p0);
        }

        // <summary>
        // A string like "Migration name not specified."
        // </summary>
        internal static string Commands_MigrationNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_MigrationNameMissing); }
        }

        // <summary>
        // A string like "Name of class to remove is missing."
        // </summary>
        internal static string Commands_RemoveClass_ClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RemoveClass_ClassNameMissing); }
        }

        // <summary>
        // A string like "Name of class for removing properties is missing."
        // </summary>
        internal static string Commands_RemoveProperties_ClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RemoveProperties_ClassNameMissing); }
        }

        // <summary>
        // A string like "Properties to remove from class {0} missing."
        // </summary>
        internal static string Commands_RemoveProperties_PropertiesMissing(object p0)
        {
            return EntityRes.GetString(EntityRes.Commands_RemoveProperties_PropertiesMissing, p0);
        }

        // <summary>
        // A string like "Cannot remove property {0} from class {1}, property does not exist."
        // </summary>
        internal static string Commands_RemoveProperties_PropertyNotFound(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.Commands_RemoveProperties_PropertyNotFound, p0, p1);
        }

        // <summary>
        // A string like "New class name missing."
        // </summary>
        internal static string Commands_RenameClass_NewClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RenameClass_NewClassNameMissing); }
        }

        // <summary>
        // A string like "Old class name missing."
        // </summary>
        internal static string Commands_RenameClass_OldClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RenameClass_OldClassNameMissing); }
        }

        // <summary>
        // A string like "Class name for renaming property missing."
        // </summary>
        internal static string Commands_RenameProperty_ClassNameMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RenameProperty_ClassNameMissing); }
        }

        // <summary>
        // A string like "New property name is missing."
        // </summary>
        internal static string Commands_RenameProperty_NewPropertyMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RenameProperty_NewPropertyMissing); }
        }

        // <summary>
        // A string like "Old property name is missing."
        // </summary>
        internal static string Commands_RenameProperty_OldPropertyMissing
        {
            get { return EntityRes.GetString(EntityRes.Commands_RenameProperty_OldPropertyMissing); }
        }

        // <summary>
        // A string like "Some operations in migration {0} may cause data loss in database! If you really want to execute this migration rerun the migrate command with -Force parameter."
        // </summary>
        internal static string DataInDbMayBeLost(object p0)
        {
            return EntityRes.GetString(EntityRes.DataInDbMayBeLost, p0);
        }

        // <summary>
        // A string like "Invalid model migration id."
        // </summary>
        internal static string InvalidModelMigrationId
        {
            get { return EntityRes.GetString(EntityRes.InvalidModelMigrationId); }
        }

        // <summary>
        // A string like "Model migrations was successfully enabled in current project."
        // </summary>
        internal static string ModelEnableSuccessfull
        {
            get { return EntityRes.GetString(EntityRes.ModelEnableSuccessfull); }
        }

        // <summary>
        // A string like "Model migrations was already enabled."
        // </summary>
        internal static string ModelMigrationsAlreadyEnabled
        {
            get { return EntityRes.GetString(EntityRes.ModelMigrationsAlreadyEnabled); }
        }

        // <summary>
        // A string like "Unable to find any migration to apply or revert."
        // </summary>
        internal static string NoMigrationsToApplyOrRevert
        {
            get { return EntityRes.GetString(EntityRes.NoMigrationsToApplyOrRevert); }
        }

        // <summary>
        // A string like "Unknown visibility {0}. Only {1} can be specified."
        // </summary>
        internal static string ParameterParser_InvalidVisibility(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.ParameterParser_InvalidVisibility, p0, p1);
        }

        // <summary>
        // A string like "Unknown property type {0}. Type is not primitive or enum."
        // </summary>
        internal static string ParameterParser_UnknownPropertyType(object p0)
        {
            return EntityRes.GetString(EntityRes.ParameterParser_UnknownPropertyType, p0);
        }

        // <summary>
        // A string like "Wrong property format, use [PropertyName]:[PropertyType], example: Name:string"
        // </summary>
        internal static string ParameterParser_WrongPropertyFormat
        {
            get { return EntityRes.GetString(EntityRes.ParameterParser_WrongPropertyFormat); }
        }

        // <summary>
        // A string like "Transformation {0} can not be applied."
        // </summary>
        internal static string PreconditionFailed(object p0)
        {
            return EntityRes.GetString(EntityRes.PreconditionFailed, p0);
        }

        // <summary>
        // A string like "Class {0} already exists in model."
        // </summary>
        internal static string Precondition_ClassExists(object p0)
        {
            return EntityRes.GetString(EntityRes.Precondition_ClassExists, p0);
        }

        // <summary>
        // A string like "Class {0} does not exist in model."
        // </summary>
        internal static string Precondition_ClassNotExists(object p0)
        {
            return EntityRes.GetString(EntityRes.Precondition_ClassNotExists, p0);
        }

        // <summary>
        // A string like "Specified path must be absolute."
        // </summary>
        internal static string ProjectExtensions_PathMustBeAbsolute
        {
            get { return EntityRes.GetString(EntityRes.ProjectExtensions_PathMustBeAbsolute); }
        }

        // <summary>
        // A string like "Specified path must be relative to project directory."
        // </summary>
        internal static string ProjectExtensions_PathMustBeRelative
        {
            get { return EntityRes.GetString(EntityRes.ProjectExtensions_PathMustBeRelative); }
        }

        // <summary>
        // A string like "More than one type with base type {0} was found."
        // </summary>
        internal static string TypeFinder_MultipleTypesFound(object p0)
        {
            return EntityRes.GetString(EntityRes.TypeFinder_MultipleTypesFound, p0);
        }

        // <summary>
        // A string like "Cannot add DbSet property to DbContext for class {0} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToAddDbSetProperty(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToAddDbSetProperty, p0);
        }

        // <summary>
        // A string like "Cannot add mapping information of type {0}. See inner exception."
        // </summary>
        internal static string VsCodeModel_FailedToAddMappingInformation(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToAddMappingInformation, p0);
        }

        // <summary>
        // A string like "Cannot add property {0} to class {1} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToAddProperty(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToAddProperty, p0, p1);
        }

        // <summary>
        // A string like "Cannot create class {0} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToCreateClass(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToCreateClass, p0);
        }

        // <summary>
        // A string like "Cannot find DbSet property for class {0} in DbContext."
        // </summary>
        internal static string VsCodeModel_FailedToFindDbSetProperty(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToFindDbSetProperty, p0);
        }

        // <summary>
        // A string like "Cannot find method {0} in class {1}."
        // </summary>
        internal static string VsCodeModel_FailedToFindMethod(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToFindMethod, p0, p1);
        }

        // <summary>
        // A string like "Cannot find property {0} in class {1}."
        // </summary>
        internal static string VsCodeModel_FailedToFindProperty(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToFindProperty, p0, p1);
        }

        // <summary>
        // A string like "Cannot remove class {0} from model project."
        // </summary>
        internal static string VsCodeModel_FailedToRemoveClass(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToRemoveClass, p0);
        }

        // <summary>
        // A string like "Cannot remove DbSet property from DbContext for class {0} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToRemoveDbSetProperty(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToRemoveDbSetProperty, p0);
        }

        // <summary>
        // A string like "Cannot remove property {0} from class {1} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToRemoveProperty(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToRemoveProperty, p0, p1);
        }

        // <summary>
        // A string like "Cannot rename class {0} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToRenameClass(object p0)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToRenameClass, p0);
        }

        // <summary>
        // A string like "Cannot rename property {0} from class {1} in model project."
        // </summary>
        internal static string VsCodeModel_FailedToRenameProperty(object p0, object p1)
        {
            return EntityRes.GetString(EntityRes.VsCodeModel_FailedToRenameProperty, p0, p1);
        }
    }

    // <summary>
    // AutoGenerated resource class. Usage:
    // string s = EntityRes.GetString(EntityRes.MyIdenfitier);
    // </summary>
    [GeneratedCode("Resources.tt", "1.0.0.0")]
    internal sealed class EntityRes
    {
        internal const string ApplyMigrationError = "ApplyMigrationError";
        internal const string BaseRunner_AssemblyNotFound = "BaseRunner_AssemblyNotFound";
        internal const string CannotBuildProject = "CannotBuildProject";
        internal const string CannotCreateCommandInstance = "CannotCreateCommandInstance";
        internal const string CannotCreateInstance = "CannotCreateInstance";
        internal const string CannotFindClassInModelProject = "CannotFindClassInModelProject";
        internal const string CannotFindConfiguration = "CannotFindConfiguration";
        internal const string CannotFindEnumInModelProject = "CannotFindEnumInModelProject";
        internal const string CannotFindMigration = "CannotFindMigration";
        internal const string CannotFindMigrationId = "CannotFindMigrationId";
        internal const string CommandNameNotSpecified = "CommandNameNotSpecified";
        internal const string Commands_AddProperties_ClassNameMissing = "Commands_AddProperties_ClassNameMissing";
        internal const string Commands_AddProperties_NoProperties = "Commands_AddProperties_NoProperties";
        internal const string Commands_CreateClass_ClassNameMissing = "Commands_CreateClass_ClassNameMissing";
        internal const string Commands_CreateClass_PropertiesMissing = "Commands_CreateClass_PropertiesMissing";
        internal const string Commands_MigrationNameMissing = "Commands_MigrationNameMissing";
        internal const string Commands_RemoveClass_ClassNameMissing = "Commands_RemoveClass_ClassNameMissing";
        internal const string Commands_RemoveProperties_ClassNameMissing = "Commands_RemoveProperties_ClassNameMissing";
        internal const string Commands_RemoveProperties_PropertiesMissing = "Commands_RemoveProperties_PropertiesMissing";
        internal const string Commands_RemoveProperties_PropertyNotFound = "Commands_RemoveProperties_PropertyNotFound";
        internal const string Commands_RenameClass_NewClassNameMissing = "Commands_RenameClass_NewClassNameMissing";
        internal const string Commands_RenameClass_OldClassNameMissing = "Commands_RenameClass_OldClassNameMissing";
        internal const string Commands_RenameProperty_ClassNameMissing = "Commands_RenameProperty_ClassNameMissing";
        internal const string Commands_RenameProperty_NewPropertyMissing = "Commands_RenameProperty_NewPropertyMissing";
        internal const string Commands_RenameProperty_OldPropertyMissing = "Commands_RenameProperty_OldPropertyMissing";
        internal const string DataInDbMayBeLost = "DataInDbMayBeLost";
        internal const string InvalidModelMigrationId = "InvalidModelMigrationId";
        internal const string ModelEnableSuccessfull = "ModelEnableSuccessfull";
        internal const string ModelMigrationsAlreadyEnabled = "ModelMigrationsAlreadyEnabled";
        internal const string NoMigrationsToApplyOrRevert = "NoMigrationsToApplyOrRevert";
        internal const string ParameterParser_InvalidVisibility = "ParameterParser_InvalidVisibility";
        internal const string ParameterParser_UnknownPropertyType = "ParameterParser_UnknownPropertyType";
        internal const string ParameterParser_WrongPropertyFormat = "ParameterParser_WrongPropertyFormat";
        internal const string PreconditionFailed = "PreconditionFailed";
        internal const string Precondition_ClassExists = "Precondition_ClassExists";
        internal const string Precondition_ClassNotExists = "Precondition_ClassNotExists";
        internal const string ProjectExtensions_PathMustBeAbsolute = "ProjectExtensions_PathMustBeAbsolute";
        internal const string ProjectExtensions_PathMustBeRelative = "ProjectExtensions_PathMustBeRelative";
        internal const string TypeFinder_MultipleTypesFound = "TypeFinder_MultipleTypesFound";
        internal const string VsCodeModel_FailedToAddDbSetProperty = "VsCodeModel_FailedToAddDbSetProperty";
        internal const string VsCodeModel_FailedToAddMappingInformation = "VsCodeModel_FailedToAddMappingInformation";
        internal const string VsCodeModel_FailedToAddProperty = "VsCodeModel_FailedToAddProperty";
        internal const string VsCodeModel_FailedToCreateClass = "VsCodeModel_FailedToCreateClass";
        internal const string VsCodeModel_FailedToFindDbSetProperty = "VsCodeModel_FailedToFindDbSetProperty";
        internal const string VsCodeModel_FailedToFindMethod = "VsCodeModel_FailedToFindMethod";
        internal const string VsCodeModel_FailedToFindProperty = "VsCodeModel_FailedToFindProperty";
        internal const string VsCodeModel_FailedToRemoveClass = "VsCodeModel_FailedToRemoveClass";
        internal const string VsCodeModel_FailedToRemoveDbSetProperty = "VsCodeModel_FailedToRemoveDbSetProperty";
        internal const string VsCodeModel_FailedToRemoveProperty = "VsCodeModel_FailedToRemoveProperty";
        internal const string VsCodeModel_FailedToRenameClass = "VsCodeModel_FailedToRenameClass";
        internal const string VsCodeModel_FailedToRenameProperty = "VsCodeModel_FailedToRenameProperty";

        private static EntityRes loader;
        private readonly ResourceManager resources;

        private EntityRes()
        {
            resources = new ResourceManager(
                "EfModelMigrations.Properties.Resources",
                typeof(EfModelMigrations.ModelMigration).Assembly);
        }

        private static EntityRes GetLoader()
        {
            if (loader == null)
            {
                var sr = new EntityRes();
                Interlocked.CompareExchange(ref loader, sr, null);
            }
            return loader;
        }

        private static CultureInfo Culture
        {
            get { return null /*use ResourceManager default, CultureInfo.CurrentUICulture*/; }
        }

        public static ResourceManager Resources
        {
            get { return GetLoader().resources; }
        }

        public static string GetString(string name, params object[] args)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }

            var res = sys.resources.GetString(name, Culture);

            if (args != null
                && args.Length > 0)
            {
                for (var i = 0; i < args.Length; i ++)
                {
                    var value = args[i] as String;
                    if (value != null
                        && value.Length > 1024)
                    {
                        args[i] = value.Substring(0, 1024 - 3) + "...";
                    }
                }
                return String.Format(CultureInfo.CurrentCulture, res, args);
            }
            else
            {
                return res;
            }
        }

        public static string GetString(string name)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }
            return sys.resources.GetString(name, Culture);
        }

        public static string GetString(string name, out bool usedFallback)
        {
            // always false for this version of gensr
            usedFallback = false;
            return GetString(name);
        }

        public static object GetObject(string name)
        {
            var sys = GetLoader();
            if (sys == null)
            {
                return null;
            }
            return sys.resources.GetObject(name, Culture);
        }
    }
}
